### ISSUE TITLE
[FEAT] 메인 뷰 UI 구현

### ISSUE THREAD

**Issue by SeoyoungOhMe** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#10]
## 🛠 Issue

메인화면 구현

## 📝 To-do

- [x] 상단의 계정 정보 구현
- [x] 광고 버튼 구현
- [x] 광고 삭제 기능 구현
- [x] 계좌 정보 구현
