### ISSUE TITLE
[FEAT] 상단 계좌 & 잔액 UI 구현

### ISSUE THREAD

**Issue by kms0233** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#14]
## 🛠 Issue

내역 및 이체 등 통장 내용 뷰에서 상단(노란 배경 영역)을 구현할 예정입니다

## 📝 To-do

- [x] 전체적인 스크롤뷰 틀 구현
- [x] 상단 navigation bar UI 구현
- [x] 계좌/잔액 텍스트 구현
- [x] 이체하기/가져오기 버튼 구현
