### ISSUE TITLE
[FEAT] '이체 뷰' 내 계좌 섹션 & 최근 계좌 섹션 & 하단 버튼 UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#16]
## 🛠 Issue
'이체 뷰' 내 계좌 섹션 & 최근 계좌 섹션 UI 구현

## 📝 To-do

- [x] '이체 뷰' 내 계좌 섹션 UI 구현
- [x] '이체 뷰' 최근 계죄 섹션 UI 구현
- [x] 하단 버튼 구현
