### ISSUE TITLE
[FIX] 코딩 컨벤션에 맞게 수정

### ISSUE THREAD

**Issue by SeoyoungOhMe** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#24]
## 🛠 Issue

코딩 컨벤션에 맞게 코드 수정

## 📝 To-do

- [x] viewDidLoad 안에 메소드만 넣기 (UI관련 설정 등등 모두 함수와 역할에 따라서 extension 으로 빼기)
- [x] setHierarchy(), setLayout() 등으로 메소드 이름 수정
- [x] UIKit 대신 Snapkit으로 구현
