### ISSUE TITLE
[Fix] 길이, 정렬, 패딩, 스크롤바, 아이콘 수정

### ISSUE THREAD

**Issue by SeoyoungOhMe** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#40]
## 🛠 Issue

- 길이, 정렬, 패딩, 스크롤바, 아이콘 수정 필요

## 📝 To-do

- [x] AccountView, SavingsView 정렬, 길이 수정
- [x] MeetingAccountView '>' 우측 패딩 재조절
- [x] AddButtonView '+' 버튼 정렬 수정
- [x] TipsViewController 스크롤바 없애기
- [x] MainTabBarController 알림 빨간색으로 변경
- [x] MessageBoxView 텍스트 좌측 정렬 수정
- [x] 스크롤해도 하단 탭 바 색 바뀌지 않도록 수정
- [x] 컬렉션뷰 좌측 패딩
