### ISSUE TITLE
[SETTING] 서버 통신 관련 기본 세팅 & 이체 서버 통신

### ISSUE THREAD

**Issue by seuriseuljjeok** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#50]
## 🛠 Issue

서버 통신 관련 기본 세팅과 이체 서버 통신

## 📝 To-do

- [x] Config 파일 추가
- [x] 기타 파일 추가
- [x] 이체 서버 통신
