### ISSUE TITLE
[FEAT] 이체 뷰 상단 네비바 & 이체 Section UI 구현

### ISSUE THREAD

**Issue by seuriseuljjeok** [NOW-SOPT-APP2-KAKAOBANK/KAKAOBANK-iOS#9]
## 🛠 Issue
이체 뷰는 Compositional Layout을 사용해서 UI를 구현할 생각입니다!
그 중에서 뷰 상단 네비바와 이체 Section UI 구현할 예정입니다

## 📝 To-do

- [x] 전체 뷰 Compositional Layout 틀 잡기
- [x] 상단 네비바 UI 구현
- [x] 이체 Section UI 구현
